Repository US-CBP/GTAS, pull requests merged in 2021-06, with the labels that each got.

#2057 Fix/lookup data updates
  gtas-parent/gtas-commons/src/main/resources/sql/airports.sql
  gtas-parent/gtas-commons/src/main/resources/sql/countries.sql
  gtas-parent/scripts/db/2.0/lookupDataUpdates.sql
Labels: bug

#2062 Added pos/neg feedback loop for POE
  gtas-parent/gtas-commons/src/main/java/gov/gtas/model/udr/json/JsonUdrListElement.java
  gtas-parent/gtas-commons/src/main/java/gov/gtas/repository/udr/UdrRuleRepository.java
  gtas-parent/gtas-commons/src/main/java/gov/gtas/services/POEServiceImpl.java
  gtas-parent/gtas-rulesvc/src/main/java/gov/gtas/svc/UdrServiceImpl.java
Labels: enhancement

#2061 Fix/unauthed request security
  gtas-parent/gtas-webapp/src/main/java/gov/gtas/controller/PreauthController.java
  gtas-parent/gtas-webapp/src/main/java/gov/gtas/controller/SignupController.java
  gtas-parent/gtas-webapp/src/main/java/gov/gtas/controller/UserController.java
  gtas-parent/gtas-webapp/src/main/java/gov/gtas/security/AppSecurityConfig.java
Labels: 3 - Review, bug

#2054 Feat/translation default text
  gtas-parent/gtas-commons/src/main/java/gov/gtas/model/Translation.java
  gtas-parent/gtas-commons/src/main/java/gov/gtas/services/TranslationServiceImpl.java
  gtas-parent/gtas-commons/src/main/java/gov/gtas/vo/TranslationVo.java
  gtas-parent/gtas-commons/src/main/resources/sql/event_report_translation_en.sql
Labels: enhancement

#2050 Fix for having Notify User user drop downs abide archived user status
  gtas-parent/gtas-commons/src/main/java/gov/gtas/services/security/UserServiceImpl.java
Labels: bug
